FROM node:alpine as builder
ENV NODE_ENV=production \
    PORT=8080

EXPOSE 8080 80

WORKDIR /app
COPY . .
RUN yarn install
RUN yarn build

FROM node:alpine as final
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY package.json .
COPY yarn.lock .
RUN yarn install --production
CMD ["node", "dist/index.js"]