version: "3"
services:
  api-server:
    image: api-server
    restart: unless-stopped
    ports:
      - "5000:80"
    networks:
      - main-app
networks:
  main-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local